/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nieltg_kociemba_CubeSolver */

#ifndef _Included_nieltg_kociemba_CubeSolver
#define _Included_nieltg_kociemba_CubeSolver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nieltg_kociemba_CubeSolver
 * Method:    isReady
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_nieltg_kociemba_CubeSolver_isReady
  (JNIEnv *, jclass);

/*
 * Class:     nieltg_kociemba_CubeSolver
 * Method:    prepare
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_nieltg_kociemba_CubeSolver_prepare
  (JNIEnv *, jclass, jstring);

/*
 * Class:     nieltg_kociemba_CubeSolver
 * Method:    solve
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_nieltg_kociemba_CubeSolver_solve
  (JNIEnv *, jclass, jstring);

/*
 * Class:     nieltg_kociemba_CubeSolver
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nieltg_kociemba_CubeSolver_destroy
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
